### ISSUE TITLE
Sync fails when library name differs from "Movies"

### ISSUE THREAD

**Issue by amatheo** [treysu/letterboxd-plex-sync#2]
**Description:**

When attempting to run the sync, it seems the script is hardcoded to look for a library named "Movies." If the Plex library uses a different name (e.g. "Films" as in my case), the sync fails and raises a `NotFound` exception.

**Logs:**

```
Starting Sync from Letterboxd to Plex
Using Plex user and library: redacted

Traceback (most recent call last):
  File "/app/sync_lb_to_plex.py", line 375, in <module>
    main()
  File "/app/sync_lb_to_plex.py", line 325, in main
    movies_library = plex.library.section('Movies')
  File "/usr/local/lib/python3.10/site-packages/plexapi/library.py", line 95, in section
    raise NotFound(f'Invalid library section: {title}') from None

plexapi.exceptions.NotFound: Invalid library section: Movies
```

**Current Setup (Portainer):**

```yaml
version: '3'
name: letterboxd-plex-sync
services:
  letterboxd-plex-sync:
    container_name: letterboxd-plex-sync
    image: treysu/letterboxd-plex-sync:latest
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - letterboxd-cache:/app/data:rw

volumes:
  letterboxd-cache:
```

**Expected Behavior:**
The script should allow specifying the Plex library name via an environment variable or configuration, rather than assuming the library is always named "Movies."

**Proposed Solution:**
- Introduce an environment variable (e.g. PLEX_LIBRARY_NAME) allowing users to specify the desired Plex library name.
- If no environment variable is set, perform a fallback: search for a "movies" type library and use the first match found.
- Update documentation to clearly explain how users can set this environment variable and how the fallback search will work.

**Comment by treysu** [comment]
Definitely an oversight on my part. I will get on a fix, hopefully completed by the end of this week (if not sooner).

**Comment by treysu** [comment]
@amatheo Please pull the latest version of the image. I have pushed a fix.

Solution:
- Fetch all 'Movie' type libraries from Plex (instead of picking by name).
- Introduce an environment variable (e.g. PLEX_LIBRARY_NAME) allowing users to specify a desired Plex library.
- If no environment variable is set, sync all "movie" type libraries.
- Updated documentation to clearly explain how users can set this environment variable.


I have updated the default behavior to automatically fetch and perform the sync on **all** 'Movie' type libraries. I have also added an environment variable `PLEX_LIBRARY_NAME` that can be used to sync only one specific library. 

See code changes [here.](https://github.com/treysu/letterboxd-plex-sync/commit/97a5661cba550d7a78ff11922eb2800aa3a1fabf)
